# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
# ROUTES NETWORK TRAFFIC TO THE REDIS POD
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend