apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  # property-like keys; each key maps to a simple value
  environment_name: "dev"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys (for creating files)
  app.properties: |
    products.types=slacks,mugs,shirts
    cart.maximum-products=50   
  user-interface.properties: |
    color.banner=green
    color.catalog=white
    allow.textmode=true